CREATE DATABASE base;
USE base;


-- TABLA USUARIOS

CREATE TABLE USUARIO (
    id_U INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    rut VARCHAR(20) NOT NULL,
    tipo ENUM ('Administrativo', 'Cliente', 'Profesional') NOT NULL
);


-- TABLA CLIENTE

CREATE TABLE CLIENTE (
    id_CL INT PRIMARY KEY AUTO_INCREMENT,
    telefono VARCHAR(100) NOT NULL,
    comuna VARCHAR(100) NOT NULL,
    id_U INT,
    FOREIGN KEY (id_U) REFERENCES USUARIO(id_U) ON DELETE CASCADE
);


-- TABLA ADMINISTRATIVO

CREATE TABLE ADMINISTRATIVO (
    id_AD INT PRIMARY KEY AUTO_INCREMENT,
    area VARCHAR(100) NOT NULL,
    experiencia_previa VARCHAR(100) NOT NULL,
    id_U INT,
    FOREIGN KEY (id_U) REFERENCES USUARIO(id_U) ON DELETE CASCADE
);


-- TABLA PROFESIONAL

CREATE TABLE PROFESIONAL (
    id_PF INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    fecha_ingreso VARCHAR(100) NOT NULL,
    id_U INT,
    FOREIGN KEY (id_U) REFERENCES USUARIO(id_U) ON DELETE CASCADE
);


-- TABLA CAPACITACIONES

CREATE TABLE CAPACITACION (
identificador INT AUTO_INCREMENT PRIMARY KEY,
dia VARCHAR(100) NOT NULL,
hora VARCHAR(100) NOT NULL,
lugar VARCHAR(100) NOT NULL,
duracion VARCHAR(100) NOT NULL,
cantidad_asistentes INT NOT NULL
);